config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  resources :pills do
  	resources :reviews
  end
  

  root 'welcome#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :pill
	validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :reviews

  has_many :pills, through: :reviews
  # has many through does not work right now, start with just adding pills to site
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pills_controller.rb
class PillsController < ApplicationController
	def new
	end

	def index
		@q = Pill.search(params[:q])
		@pills = @q.result
		# @search = Pill.search(params[:q])
		# @pills = @search.result
	end

	def show
		@pill = Pill.find(params[:id])
		@reviews = Review.where(pill_id: params[:id])
		@count = []
		@reviews.each do |review|
			@count.push(review.title)
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@review = Review.new
		@pill = Pill.find(params[:pill_id])

		
		if current_user
			@user = current_user.id
		else
			@user = "no user signed in"
		end
	end

	def create
		@review = Review.new(review_params)
		@review.user_id = current_user.id
		@review.pill_id = params[:pill_id]
		if @review.save
			redirect_to pill_path(params[:pill_id])
		else
			render 'new'
		end
	end

	def show
		@pill = Pill.find(params[:pill_id])
		@review = @pill.reviews.find(params[:id])
	end

	def index
		@reviews = Review.all
		@reviews = Review.where(pill_id: params[:pill_id])
		
	end

	def edit
		@review = Review.find(params[:id])
	end

	def update
		@review = Review.find(params[:id])

		if @review.update(review_params)
			redirect_to @review
		else
			render 'edit'
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy

		redirect_to reviews_path
		
	end

	private
  	def review_params
    	params.require(:review).permit(:title,:text)
  	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # def index
  # 	@user = current_user
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pills_helper.rb
module PillsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div class="fixed">
	<nav class="top-bar green" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<h1><%= link_to "Home", root_path %></h1>
			</li>
		</ul>
		<ul class="left">
			<li class="name">
				<h1><%= link_to "All", pills_path %></h1>
			</li>
		</ul>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   

    <title><%= content_for?(:title) ? yield(:title) : "Hormonal Birth Control" %></title>

    <%= stylesheet_link_tag    "application" %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "layouts/header" %>
    <%= yield %>
    
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
  </body>
</html>

app/views/pills/index.html.erb
<div class="centerElements">
	<h1>All Pills</h1>
</div>

<%= search_form_for @q do |f|%>

	<div class="row">
		<div class="small-4 columns">
			<%= f.label :name_cont, "Pill Name" %>
			<%= f.search_field :name_cont %>
		</div>
		<div class="small-4 columns">
			<%= f.label :hormone_cont, "Hormone Name" %>
			<%= f.search_field :hormone_cont %>
		</div>
		<div class="small-3 small-offset-1 columns" style="padding-top: 0.5em">
			<%= f.submit "Search", :class => "button green" %>
		</div>
	</div>
<%end %>




<div class="allPills">
	<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
		<% @pills.each do |pill| %>
			<li class="pillCard">
				<%= link_to pill.name, pill_path(pill), :class => "pillName" %>
				<div class="pillHormone hidden"><%= pill.hormone %></div>
			</li>
		<%end%>
	</ul>
</div>

app/views/pills/new.html.erb
This is where new pills will go...

<%=@pills %>

app/views/pills/show.html.erb
<div class="row">
	<div class="row">
	  	<div class="centerElements">
	  		<h1 class="headline"><%= @pill.name %></h1>
	  	</div>

		<div class="centerElements">
	  		<%= @pill.hormone %>
		</div>
	</div>


<% if @reviews.length > 0 %>
  <div class="reviews">
    <table>
      <thead class="tableHeadline">
        <tr >
          <th width="150">Title</th>
          <th width ="350">Review</th>
        </tr>
      </thead>
      <tbody>
        <%@reviews.each do |review| %>
          <tr>
            <td><%= review.title %></td>
            <td><%= review.text %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
<%end %>


<div class="centerElements">
	<% if current_user %>
		<%= link_to 'Add a new review', new_pill_review_path(@pill, @review), :class => "button green" %>
	<%else %>
		You must sign in or sign up to write a review
		<%= link_to "Sign in", new_user_session_path, :method => :get %>
		<%= link_to "Sign up", new_user_registration_path, :method => :get %>
	<%end %>
</div>

app/views/reviews/_form.html.erb
<%= form_for :review, url: pill_reviews_path do |f| %> 
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited
      this review from being saved:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <%= f.label :title, :class => "right inline" %>
      </div>
      <div class="small-9 columns">
        <%= f.text_field :title, :id => "right-label" %>
      </div>
    </div>
  </div>
</div>
  
<div class="row">
  <div class="small-8">
    <div class="row">
      <div class="small-3 columns">
        <%= f.label :text, :class=>"right inline" %>
      </div>
      <div class="small-9 columns">
        <%= f.text_area :text, :id => "right-label"%>
      </div>
    </div>
  </div>
</div>

<div>
<%= f.submit "Save Review", :class=>"button green"%>
</div>
<% end %>

app/views/reviews/edit.html.erb
<h1> Edit a Review</h1>

<%= render 'form' %>
 
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<%= link_to 'New review', new_pill_review_path %>



<h1>Listing reviews</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th> User Id </th>
    <th>Pill Id </th>
  </tr>

  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= review.user_id %></td>
      <td><%= review.pill_id %></td>

    </tr>
  <% end %>
</table>



<%= link_to "All Pills", pills_path %><br/>

app/views/reviews/new.html.erb
<div class="row">
	<div class="row">
		<div class="row">
		  	<div class="centerElements">
		  		<h1 class="headline">New Review for <%=@pill.name %></h1>
		  	</div>
		</div>
	</div>


	<%= render 'form' %>


</div>

app/views/reviews/show.html.erb
<%= params.inspect %>
<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>

<%= link_to 'Back', reviews_path %> | <%= link_to 'Edit', edit_review_path(@review) %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="introPage">
	<div class = "centerElements info">
		<h1>What's in your birth control</h1>
		<p> Here is where you can find information about hormonal birth control methods and user reivews.  This is NOT a medical site, just something that interests me. Go to all pills to find out which pills have which hormones, and sign in to write reviews</p>
	</div>

	<div class="centerElements">
		<%= link_to "All Pills", pills_path, :class=> "button green" %>
			<br/>
		<% if user_signed_in? %>
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class=> "button green"%>
		<% else %>
			<%= link_to "Sign in", new_user_session_path, :method => :get, :class=> "button green" %>
			<%= link_to "Sign up", new_user_registration_path, :method => :get, :class=> "button green" %>
		<%end %>
	</div>
</div>